from typing import Any


BUILTIN_FEATURE_TEMPLATES: list[dict[str, Any]] = [
    {
        "id": "builtin:nginx_access",
        "scope": "builtin",
        "name": "Nginx 访问日志特征模板",
        "log_type": "nginx_access",
        "description": "适合 Nginx 访问日志，保留原字段并追加路径、状态码、UA 和流量相关特征。",
        "field_hints": {
            "required_columns": ["path", "status_code"],
            "optional_columns": ["event_time", "method", "user_agent", "bytes_sent", "request_duration"],
        },
        "steps": [
            {
                "step_id": "nginx_path_features",
                "step_type": "path_features",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["path"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns"},
            },
            {
                "step_id": "nginx_status_category",
                "step_type": "status_category",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["status_code"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns"},
            },
            {
                "step_id": "nginx_method_encode",
                "step_type": "category_encode",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["method"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_code"},
            },
            {
                "step_id": "nginx_ua_length",
                "step_type": "text_length",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["user_agent"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_length"},
            },
            {
                "step_id": "nginx_path_entropy",
                "step_type": "shannon_entropy",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["path"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_entropy"},
            },
            {
                "step_id": "nginx_ua_complexity",
                "step_type": "char_composition",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["user_agent"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns"},
            },
            {
                "step_id": "nginx_admin_flag",
                "step_type": "boolean_flag",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["path"]},
                "params": {"operator": "contains", "value": "admin"},
                "output_mode": {"mode": "append_new_columns", "output_column": "path_has_admin"},
            },
            {
                "step_id": "nginx_bytes_bucket",
                "step_type": "numeric_bucket",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["bytes_sent"]},
                "params": {"bins": 5},
                "output_mode": {"mode": "append_new_columns", "suffix": "_bucket"},
            },
            {
                "step_id": "nginx_duration_bucket",
                "step_type": "numeric_bucket",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["request_duration"]},
                "params": {"bins": 5},
                "output_mode": {"mode": "append_new_columns", "suffix": "_bucket"},
            },
        ],
    },
    {
        "id": "builtin:program_runtime",
        "scope": "builtin",
        "name": "程序运行日志特征模板",
        "log_type": "program_runtime",
        "description": "适合程序运行和应用日志，突出 severity、文本长度、关键词和主机/进程频次。",
        "field_hints": {
            "required_columns": ["raw_message"],
            "optional_columns": ["severity", "host", "process_name", "event_time"],
        },
        "steps": [
            {
                "step_id": "runtime_severity_map",
                "step_type": "value_map",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["severity"]},
                "params": {
                    "mapping": {"low": 1, "medium": 2, "high": 3, "critical": 4, "error": 4, "warn": 2},
                    "default_value": 0,
                },
                "output_mode": {"mode": "append_new_columns", "suffix": "_score"},
            },
            {
                "step_id": "runtime_message_length",
                "step_type": "text_length",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["raw_message"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_length"},
            },
            {
                "step_id": "runtime_message_entropy",
                "step_type": "shannon_entropy",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["raw_message"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_entropy"},
            },
            {
                "step_id": "runtime_keyword_count",
                "step_type": "keyword_count",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["raw_message"]},
                "params": {"keywords": ["error", "exception", "failed", "timeout", "denied"]},
                "output_mode": {"mode": "append_new_columns", "output_column": "raw_message_keyword_hits"},
            },
            {
                "step_id": "runtime_pattern_flags",
                "step_type": "pattern_flags",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["raw_message"]},
                "params": {"patterns": ["ip", "url", "hash", "base64_like", "email"]},
                "output_mode": {"mode": "append_new_columns"},
            },
            {
                "step_id": "runtime_host_frequency",
                "step_type": "frequency_encode",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["host"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_freq"},
            },
            {
                "step_id": "runtime_process_frequency",
                "step_type": "frequency_encode",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["process_name"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_freq"},
            },
        ],
    },
    {
        "id": "builtin:nta_flow",
        "scope": "builtin",
        "name": "NTA 流量日志特征模板",
        "log_type": "nta_flow",
        "description": "适合网络流量和会话日志，突出 IP、端口、协议和流量大小相关特征。",
        "field_hints": {
            "required_columns": ["source_ip", "dest_ip"],
            "optional_columns": ["src_port", "dest_port", "protocol", "bytes", "duration", "host", "domain", "source_host", "dest_host"],
        },
        "steps": [
            {
                "step_id": "nta_source_ip",
                "step_type": "ip_features",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["source_ip", "dest_ip"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns"},
            },
            {
                "step_id": "nta_port_features",
                "step_type": "port_features",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["src_port", "dest_port"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns"},
            },
            {
                "step_id": "nta_protocol_map",
                "step_type": "value_map",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["protocol"]},
                "params": {"mapping": {"tcp": 1, "udp": 2, "icmp": 3}, "default_value": 0},
                "output_mode": {"mode": "append_new_columns", "suffix": "_code"},
            },
            {
                "step_id": "nta_domain_entropy",
                "step_type": "shannon_entropy",
                "enabled": True,
                "input_selector": {"mode": "role_tag", "role_tag": "domain"},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "suffix": "_entropy"},
            },
            {
                "step_id": "nta_bytes_bucket",
                "step_type": "numeric_bucket",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["bytes"]},
                "params": {"bins": 5},
                "output_mode": {"mode": "append_new_columns", "suffix": "_bucket"},
            },
            {
                "step_id": "nta_duration_bucket",
                "step_type": "numeric_bucket",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["duration"]},
                "params": {"bins": 5},
                "output_mode": {"mode": "append_new_columns", "suffix": "_bucket"},
            },
            {
                "step_id": "nta_flow_pair_count",
                "step_type": "group_frequency",
                "enabled": True,
                "input_selector": {"mode": "explicit", "columns": ["source_ip", "dest_ip"]},
                "params": {},
                "output_mode": {"mode": "append_new_columns", "output_column": "flow_pair_count"},
            },
        ],
    },
]
